project_id = "ipysjdhvimlxdoszfamo"

[functions.create-notification]
verify_jwt = true

[functions.send-notification-email]
verify_jwt = true

[functions.upsert-user-with-profile]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false