// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djfohxpjrvoljatjwjec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqZm9oeHBqcnZvbGphdGp3amVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NTY1NDQsImV4cCI6MjA2NTIzMjU0NH0.LiRlX766Gb7e0lTzdbnIBgurKMo2-sFI7MwxoEJoq2o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);