// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jesgpyuomsvpfmbgqzhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Implc2dweXVvbXN2cGZtYmdxemhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MzgzMzQsImV4cCI6MjA3MDAxNDMzNH0.QYuaxNEOIGe1HnRFdMFAzIz_8S3za9bT9dF9HwWF_do";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});